project:
  type: website

website:
  title: "L'homme à la houe"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: darkly
    css: styles.css

editor: visual

